docker_stacks:
  - { name: utils,     path: utils }
  - { name: glance,    path: glance }
  - { name: homepage,  path: homepage }
  - { name: metrics,   path: metrics }
  - { name: rustdesk,  path: apps/rustdesk }
  - { name: portainer, path: portainer, env: false }
docker_stacks_wait_for_mounts:
  - /mnt/ssdnas