all:
  children:
    linux:
      vars:
        ansible_user: ansible
        ansible_become: true
      children:
        proxmox:
          hosts:
            pve01: { ansible_host: 192.168.0.14 }
        guests:
          hosts:
            caddy:    { ansible_host: 192.168.0.25,}
            pbs:      { ansible_host: 192.168.0.181 }
            docker01: { ansible_host: 192.168.0.15 }
            monitoring01: { ansible_host: 192.168.0.17 }
            adguard:      { ansible_host: 192.168.0.29 }
            tailscale:    { ansible_host: 192.168.0.50 }

    macs:
      hosts:
        macmini: { ansible_host: 192.168.0.26, ansible_user: rubenclaes }
        mbp:     { ansible_connection: local }