- name: Create the Semaphore LXC
  hosts: pve01
  vars:
    lxc_vmid: 104
    lxc_hostname: semaphore
    lxc_ip: 192.168.0.30/24
    lxc_gateway: 192.168.0.1
    lxc_template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
    pve_api: &pve_api
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_token_id: "{{ pve_api_token_id }}"
      api_token_secret: "{{ pve_api_token_secret }}"
      validate_certs: false
  tasks:
    - name: Create the container
      community.proxmox.proxmox:
        <<: *pve_api
        node: "{{ ansible_facts['hostname'] }}"
        vmid: "{{ lxc_vmid }}"
        hostname: "{{ lxc_hostname }}"
        ostemplate: "{{ lxc_template }}"
        disk_volume:
          storage: local-lvm
          size: 8
        cores: 2
        memory: 2048
        swap: 512
        unprivileged: true
        features:
          - nesting=1
        netif:
          net0: "name=eth0,bridge=vmbr0,ip={{ lxc_ip }},gw={{ lxc_gateway }}"
        pubkey: "{{ lookup('file', '~/.ssh/ansible_ed25519.pub') }}"
        onboot: true
        cmode: tty
        state: present
      delegate_to: localhost
      become: false

    - name: Start the container
      community.proxmox.proxmox:
        <<: *pve_api
        node: "{{ ansible_facts['hostname'] }}"
        vmid: "{{ lxc_vmid }}"
        hostname: "{{ lxc_hostname }}"
        state: started
      delegate_to: localhost
      become: false
      register: start_result
      retries: 6
      delay: 5
      until: start_result is succeeded